/* 局域网模式以服务端为准；file: 本地模式使用浏览器存储。 */
const $ = (s) => document.querySelector(s);
const uuidv4 = () => { if (typeof crypto !== 'undefined' && crypto.randomUUID) return crypto.randomUUID(); return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => { const r = Math.random() * 16 | 0; return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16); }); };
const storeKey = 'motor-atlas-documents-v1';
const categoriesKey = 'motor-atlas-categories-v1';
const trashKey = 'motor-atlas-trash-v1';
const userKey = 'motor-atlas-user-v1';
const activityKey = 'motor-atlas-activity-v1';
const readingHistoryKey = 'motor-atlas-reading-history-v1';
const databaseName = 'hd-motors-knowledge-db';
const databaseStore = 'state';
const pdfStore = 'pdf-files';
const presentationStore = 'presentation-files';
let databasePromise = null;
function getDatabase(){if(databasePromise)return databasePromise;databasePromise=new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(new Error('浏览器不支持 IndexedDB'));const request=indexedDB.open(databaseName,3);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(databaseStore))request.result.createObjectStore(databaseStore);if(!request.result.objectStoreNames.contains(pdfStore))request.result.createObjectStore(pdfStore);if(!request.result.objectStoreNames.contains(presentationStore))request.result.createObjectStore(presentationStore)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return databasePromise}
async function savePdfBlob(id,blob){const db=await getDatabase();return new Promise((resolve,reject)=>{const request=db.transaction(pdfStore,'readwrite').objectStore(pdfStore).put(blob,id);request.onsuccess=resolve;request.onerror=()=>reject(request.error)})}
async function getPdfBlob(id){if(isLanMode&&id){try{return await remoteAttachmentBlob({attachmentId:id},'PDF')}catch(error){console.warn('局域网 PDF 读取失败',error);return null}}try{const db=await getDatabase();return await new Promise((resolve,reject)=>{const request=db.transaction(pdfStore).objectStore(pdfStore).get(id);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error)})}catch(error){console.warn('PDF 读取失败',error);return null}}
async function deletePdfBlob(id){try{const db=await getDatabase();await new Promise((resolve,reject)=>{const request=db.transaction(pdfStore,'readwrite').objectStore(pdfStore).delete(id);request.onsuccess=resolve;request.onerror=()=>reject(request.error)})}catch(error){console.warn('PDF 删除失败',error)}}
async function savePresentationBlob(id,blob){const db=await getDatabase();return new Promise((resolve,reject)=>{const request=db.transaction(presentationStore,'readwrite').objectStore(presentationStore).put(blob,id);request.onsuccess=resolve;request.onerror=()=>reject(request.error)})}
async function getPresentationBlob(id){if(isLanMode&&id){try{return await remoteAttachmentBlob({attachmentId:id},'PPTX')}catch(error){console.warn('局域网 PPTX 读取失败',error);return null}}try{const db=await getDatabase();return await new Promise((resolve,reject)=>{const request=db.transaction(presentationStore).objectStore(presentationStore).get(id);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error)})}catch(error){console.warn('PPTX 读取失败',error);return null}}
async function deletePresentationBlob(id){try{const db=await getDatabase();await new Promise((resolve,reject)=>{const request=db.transaction(presentationStore,'readwrite').objectStore(presentationStore).delete(id);request.onsuccess=resolve;request.onerror=()=>reject(request.error)})}catch(error){console.warn('PPTX 删除失败',error)}}
async function saveToDatabase(){try{const db=await getDatabase();await new Promise((resolve,reject)=>{const request=db.transaction(databaseStore,'readwrite').objectStore(databaseStore).put({docs,categories,trash,activities},'library');request.onsuccess=resolve;request.onerror=()=>reject(request.error)});return true}catch(error){console.error('IndexedDB 保存失败',error);return false}}
async function loadFromDatabase(){if(isLanMode)return null;try{const db=await getDatabase();return await new Promise((resolve,reject)=>{const request=db.transaction(databaseStore).objectStore(databaseStore).get('library');request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error)})}catch(error){console.warn('IndexedDB 读取失败',error);return null}}
function readLocal(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch(e){console.warn('本地资料损坏，已使用安全副本',e);return null}}
let docs = readLocal(storeKey) || seedDocs();
let trash = readLocal(trashKey) || [];
let currentUser = readLocal(userKey) || { name: '管理员', role: 'admin' };
let activities = readLocal(activityKey) || [];
const standardCategories = [{name:'国家标准',color:'#c56a55'},{name:'行业标准',color:'#738dae'},{name:'设计手册',color:'#6f9b84'},{name:'企业标准',color:'#9777a8'},{name:'未定义',color:'#8c9692'}];
let categories = readLocal(categoriesKey) || standardCategories;
const oldCategoryNames = ['电磁设计','结构工艺','试验与标准'];
if (categories.length === oldCategoryNames.length && categories.every(category => oldCategoryNames.includes(category.name))) { const migration={电磁设计:'设计手册',结构工艺:'设计手册',试验与标准:'国家标准'}; docs.forEach(doc=>doc.category=migration[doc.category]||doc.category); trash.forEach(doc=>doc.category=migration[doc.category]||doc.category); categories=standardCategories; }
if (!categories.some(category => category.name === '未定义')) categories.push({name:'未定义',color:'#8c9692'});
let view = 'recent', filter = 'all', activeDoc = null, layoutMode = 'grid', pendingFiles = [], noteSaving = false, importingFiles = false, remoteSearchIds = null, remoteSearchVersion = 0, visibleDocumentLimit = 20;
const isLanMode = location.protocol === 'http:' || location.protocol === 'https:';
const getReadingHistory = () => readLocal(`${readingHistoryKey}:${isLanMode ? currentUser.name : 'local'}`) || {};
const saveReadingHistory = history => { try { localStorage.setItem(`${readingHistoryKey}:${isLanMode ? currentUser.name : 'local'}`,JSON.stringify(history)); } catch(error) { console.warn('阅读记录保存失败',error); } };
const remoteRequest = async (path, options={}) => { const response=await fetch(path,{credentials:'same-origin',...options}); const data=await response.json().catch(()=>({})); if(response.status===401&&isLanMode){try{localStorage.removeItem(userKey)}catch{}const next=`${location.pathname}${location.search}${location.hash}`;location.replace(`/login.html?next=${encodeURIComponent(next)}`);throw new Error('登录已过期，正在返回登录页')} if(!response.ok)throw new Error(data.error||'局域网服务请求失败'); return data; };
const remotePayload = doc => ({id:doc.id,title:doc.title,category:doc.category,type:doc.type,tags:doc.tags||[],content:(doc.content||'').replaceAll('__ATTACHMENT__',doc.attachmentId||doc.id),metadata:{favorite:!!doc.favorite,pdfId:doc.pdfId||null,pdfPages:doc.pdfPages||null,presentationId:doc.presentationId||null,attachmentId:doc.attachmentId||null,attachmentName:doc.attachmentName||null}});
const remoteDoc = row => { let tags=[],metadata={}; try{tags=JSON.parse(row.tags_json||'[]')}catch{} try{metadata=JSON.parse(row.metadata_json||'{}')}catch{} const attachmentId=metadata.attachmentId||null,contentLoaded=Object.prototype.hasOwnProperty.call(row,'content'),content=row.content||'',text=(row.summary||content.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()).slice(0,180); return {id:row.id,title:row.title,type:row.type,category:row.category||'未分类',tags,updated:Date.parse(row.updated_at)||Date.now(),created:Date.parse(row.created_at)||Date.now(),createdBy:row.created_by||'系统迁移',favorite:!!row.favorite,content,summary:text,contentLoaded,pdfId:metadata.pdfId||attachmentId,pdfPages:metadata.pdfPages||null,presentationId:metadata.presentationId||attachmentId,attachmentId,attachmentName:metadata.attachmentName||null}; };
async function uploadRemoteAttachment(id,blob){if(!blob)return;await remoteRequest(`/api/attachments/${id}`,{method:'PUT',headers:{'Content-Type':blob.type||'application/octet-stream'},body:blob})}
async function createRemoteDoc(doc,attachment){if(!isLanMode)return;doc.createdBy=currentUser.name;let uploaded=false;try{if(attachment){doc.attachmentId=doc.id;doc.attachmentName=attachment.name||doc.title;if(doc.type==='image')doc.content=`<img src="/api/attachments/__ATTACHMENT__" alt="${escapeHtml(doc.title)}" loading="lazy" />`;await uploadRemoteAttachment(doc.id,attachment);uploaded=true}await remoteRequest('/api/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(remotePayload(doc))})}catch(error){if(uploaded)remoteRequest(`/api/attachments/${doc.id}`,{method:'DELETE'}).catch(cleanupError=>console.warn('未关联附件清理失败',cleanupError));throw error}}
async function updateRemoteDoc(doc){if(!isLanMode)return;await remoteRequest(`/api/documents/${doc.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(remotePayload(doc))})}
async function updateRemoteFavorite(doc){if(!isLanMode)return;await remoteRequest(`/api/documents/${doc.id}/favorite`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({favorite:!!doc.favorite})})}
async function syncRemoteLibrary(){if(!isLanMode)return;const [live,bin,remoteCategories]=await Promise.all([remoteRequest('/api/documents'),remoteRequest('/api/documents/trash').catch(()=>({documents:[]})),remoteRequest('/api/categories').catch(()=>({categories:[]}))]);const history=getReadingHistory();docs=(live.documents||[]).map(row=>{const doc=remoteDoc(row);return {...doc,lastRead:Number(history[doc.id])||undefined}});trash=(bin.documents||[]).map(remoteDoc);if(remoteCategories.categories?.length)categories=remoteCategories.categories;const names=[...new Set(docs.concat(trash).map(doc=>doc.category).filter(Boolean))];names.forEach(name=>{if(!categories.some(category=>category.name===name))categories.push({name,color:'#8c9d7e'})});save();renderDocs();if($('#searchInput').value.trim())await refreshRemoteSearch();const requested=new URLSearchParams(location.search).get('doc');if(requested)openDoc(requested);}

function seedDocs() { return [
  {id:'welcome',title:'欢迎来到电机设计知识库',type:'document',category:'设计手册',tags:['使用指南','知识管理'],updated:Date.now(),created:Date.now(),lastRead:Date.now(),favorite:false,content:'<h2>资料，应该随时可以读</h2><p>这里是一个本地优先的知识库。你可以直接拖入 <strong>Word、Excel、PDF、Markdown、HTML、图片</strong>等资料，系统会将其转为适合网页阅读的内容。</p><h3>快速开始</h3><ol><li>点击左侧“导入资料”，或将文件拖到页面中。</li><li>为资料选择分类，使用上方搜索快速定位。</li><li>星标收藏关键文档；所有内容保存在当前浏览器中。</li></ol><blockquote>建议使用 Markdown 写笔记，Word 和 Excel 用于沉淀既有资料。</blockquote>'},
  {id:'example',title:'永磁同步电机：初步设计检查表',type:'document',category:'设计手册',tags:['PMSM','设计流程'],updated:Date.now()-86400000,created:Date.now()-86400000,lastRead:Date.now()-86400000,favorite:true,content:'<h2>设计输入</h2><table><thead><tr><th>项目</th><th>确认内容</th></tr></thead><tbody><tr><td>额定工况</td><td>转速、转矩、电压、工作制</td></tr><tr><td>边界条件</td><td>外形、冷却、成本与噪声</td></tr></tbody></table><h2>关键校核</h2><p>确认气隙磁密、齿部饱和、反电势和弱磁能力，并在额定点及极限工况下核算温升。</p>'}
] }
function notify(message,kind='info'){const toast=$('#toast');toast.textContent=message;toast.dataset.kind=kind;toast.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.hidden=true,3500)}
function save(){if(isLanMode){try{localStorage.setItem(activityKey,JSON.stringify(activities))}catch(error){console.warn('局域网操作记录缓存保存失败',error)}return true}let localSaved=true;try{localStorage.setItem(storeKey,JSON.stringify(docs));localStorage.setItem(categoriesKey,JSON.stringify(categories));localStorage.setItem(trashKey,JSON.stringify(trash));localStorage.setItem(activityKey,JSON.stringify(activities))}catch(e){localSaved=false;console.warn('localStorage 容量不足，已改用 IndexedDB 保存',e);notify('本地资料较大，已使用大容量本地存储保存。','info')}saveToDatabase().then(ok=>{if(!ok)notify('本地存储不可用，请导出或保留原始文件备份。','warn')});return localSaved||!!window.indexedDB}
function logActivity(action,target){activities.unshift({id:uuidv4(),action,target,user:currentUser.name,time:Date.now()});activities=activities.slice(0,200)}
function canEdit(){return currentUser.role==='admin'||currentUser.role==='editor'}
function canManage(){return currentUser.role==='admin'}
function requireEdit(){if(canEdit())return true;notify('当前为只读访客，没有编辑权限。','warn');return false}
let editingCategories=false;const updateCategoryEditMode=()=>{const el=$('#categoryList'),edit=$('#editCategories'),add=$('#addCategory');if(el)el.classList.toggle('editing-categories',editingCategories);if(edit){edit.classList.toggle('active',editingCategories);edit.textContent=editingCategories?'✓ 完成':'✎'}if(add)add.hidden=!editingCategories;renderDocs()};function applyPermissions(){const label={admin:'管理员',editor:'编辑者',viewer:'只读访客'}[currentUser.role]||'只读访客',initial=currentUser.name.slice(0,1)||'访';$('#userAvatar').textContent=initial;$('#profileAvatar').textContent=initial;$('#profileName').textContent=currentUser.name||'访客';$('#userRole').textContent=label;['#importButton','#emptyImport','#newNote','#deleteButton','#editDocButton','#restoreButton','#saveNote'].forEach(selector=>{const element=$(selector);if(element)element.disabled=!canEdit()});const importSubmit=$('#importForm button[type="submit"]');if(importSubmit)importSubmit.disabled=!canEdit();const addCategory=$('#addCategory');if(addCategory)addCategory.disabled=!canManage();const editCat=$('#editCategories');if(editCat)editCat.hidden=!canManage();if(!canManage()){editingCategories=false;updateCategoryEditMode()}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function typeLabel(t){return ({document:'文档',sheet:'表格',pdf:'PDF',presentation:'PPT',image:'图片'})[t]||'资料'}
function parseTags(value){return [...new Set(String(value||'').split(/[,，]/).map(tag=>tag.trim()).filter(Boolean).slice(0,8))]}
function formatDate(t){return new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric'}).format(t)}
function sanitizeHtml(html){const doc=new DOMParser().parseFromString(html||'','text/html');doc.querySelectorAll('script,style,iframe,object,embed,link,meta,base,form,button,input,textarea,select,option,svg,math').forEach(el=>el.remove());doc.querySelectorAll('*').forEach(el=>{[...el.attributes].forEach(a=>{const name=a.name.toLowerCase(),value=a.value.replace(/[\u0000-\u0020]/g,'').toLowerCase();if(name.startsWith('on')||['style','srcdoc','formaction','xlink:href'].includes(name)||((name==='src'||name==='href')&&(value.startsWith('javascript:')||value.startsWith('vbscript:')||(value.startsWith('data:')&&!value.startsWith('data:image/')))))el.removeAttribute(a.name)});if(el.tagName==='A'){el.setAttribute('rel','noopener noreferrer');if(el.getAttribute('target')!=='_blank')el.removeAttribute('target')}});return doc.body.innerHTML}
function summary(d){const text=d.summary||(d.content||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();return text.slice(0,85)||'暂无文本内容'}
function fullText(d){return (d.content||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function highlightText(value){const text=String(value??''),query=$('#searchInput')?.value.trim();if(!query)return escapeHtml(text);const escaped=query.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return escapeHtml(text).replace(new RegExp(`(${escaped})`,'gi'),'<mark>$1</mark>')}
function highlightArticle(){const query=$('#searchInput')?.value.trim();const root=$('#articleContent');if(!query||!root)return;const pattern=new RegExp(query.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'gi');const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode()){const parent=walker.currentNode.parentElement;if(parent&&!['SCRIPT','STYLE','MARK'].includes(parent.tagName)&&pattern.test(walker.currentNode.nodeValue))nodes.push(walker.currentNode);pattern.lastIndex=0}nodes.forEach(node=>{const fragment=document.createDocumentFragment();let cursor=0;node.nodeValue.replace(pattern,(match,index)=>{fragment.append(document.createTextNode(node.nodeValue.slice(cursor,index)));const mark=document.createElement('mark');mark.textContent=match;fragment.append(mark);cursor=index+match.length;return match});fragment.append(document.createTextNode(node.nodeValue.slice(cursor)));node.replaceWith(fragment)})}
function renderCategories(){const el=$('#categoryList');el.innerHTML=categories.map(c=>`<button class="nav-item category${view===`category:${c.name}`?' active':''}" data-category="${escapeHtml(c.name)}"><i class="category-dot" style="background:${c.color}"></i><span class="category-name">${escapeHtml(c.name)}</span><em>${docs.filter(d=>d.category===c.name).length}</em>${c.name!=='未定义'&&editingCategories&&canManage()?`<span class="category-delete" data-delete-category="${escapeHtml(c.name)}" title="删除分类" role="button" aria-label="删除 ${escapeHtml(c.name)}">×</span>`:''}</button>`).join('');$('#noteCategory').innerHTML=categories.map(c=>`<option>${escapeHtml(c.name)}</option>`).join('')}
async function deleteCategory(name){if(name==='未定义')return;const count=docs.filter(doc=>doc.category===name).length+trash.filter(doc=>doc.category===name).length;if(!confirm(`删除“${name}”？其中 ${count} 份资料将自动移入“未定义”。`))return;try{if(isLanMode)await remoteRequest(`/api/categories/${encodeURIComponent(name)}`,{method:'DELETE'});docs.forEach(doc=>{if(doc.category===name)doc.category='未定义'});trash.forEach(doc=>{if(doc.category===name)doc.category='未定义'});categories=categories.filter(category=>category.name!==name);save();renderDocs();notify('分类已删除，资料已移入“未定义”','success')}catch(error){notify(error.message||'删除分类失败','warn')}}
function baseResults(){const source=view==='trash'?trash:docs;const q=$('#searchInput').value.trim().toLowerCase();return source.filter(d=>{if(view==='favorites'&&!d.favorite)return false;if(view==='recent'&&!d.lastRead)return false;if(view==='latest'&&d.created<=Date.now()-7*864e5)return false;if(view.startsWith('category:')&&d.category!==view.slice(9))return false;if(!q)return true;if(isLanMode&&view!=='trash'&&remoteSearchIds instanceof Set)return remoteSearchIds.has(d.id);return [d.title,d.category,(d.tags||[]).join(' '),d.summary||'',fullText(d)].join(' ').toLowerCase().includes(q)})}
function currentDocs(){const all=baseResults();const matched=filter==='all'?all:all.filter(d=>d.type===filter);const sort=view==='latest'?'created':$('#sortSelect').value;if(view==='recent'&&sort==='updated')return matched.sort((a,b)=>(b.lastRead||0)-(a.lastRead||0));return matched.sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'zh'):sort==='created'?b.created-a.created:b.updated-a.updated)}
async function refreshRemoteSearch(){const query=$('#searchInput').value.trim(),version=++remoteSearchVersion;visibleDocumentLimit=100;if(!query||!isLanMode){remoteSearchIds=null;renderDocs();return}remoteSearchIds=new Set();renderDocs();try{const result=await remoteRequest(`/api/documents/search?q=${encodeURIComponent(query)}`);if(version!==remoteSearchVersion)return;remoteSearchIds=new Set(result.ids||[]);renderDocs();if(result.truncated)notify('匹配结果较多，当前显示前 500 份，请增加关键词缩小范围。','info')}catch(error){if(version!==remoteSearchVersion)return;remoteSearchIds=null;renderDocs();notify(error.message||'全文搜索暂时不可用','warn')}}
function renderDocs(){renderCategories();const viewFiltered=baseResults();const results=currentDocs();const visible=results.slice(0,visibleDocumentLimit),grid=$('#documentGrid'),more=$('#loadMoreDocs');$('#docCount').textContent=docs.length;$('#latestCount').textContent=docs.filter(d=>d.created>Date.now()-7*864e5).length;$('#allTotal').textContent=viewFiltered.length;$('#favoriteCount').textContent=docs.filter(d=>d.favorite).length;$('#recentCount').textContent=docs.filter(d=>d.lastRead).length;$('#trashCount').textContent=trash.length;$('#docTypeCount').textContent=viewFiltered.filter(d=>d.type==='document').length;$('#sheetTypeCount').textContent=viewFiltered.filter(d=>d.type==='sheet').length;$('#pdfTypeCount').textContent=viewFiltered.filter(d=>d.type==='pdf').length;$('#imageTypeCount').textContent=viewFiltered.filter(d=>d.type==='image').length;$('#pptTypeCount').textContent=viewFiltered.filter(d=>d.type==='presentation').length;grid.classList.toggle('list-view',layoutMode==='list');grid.classList.toggle('compact-grid',layoutMode==='compact');grid.innerHTML=visible.map(d=>`<article class="doc-card type-${escapeHtml(d.type)}" data-id="${escapeHtml(d.id)}" aria-label="${escapeHtml(typeLabel(d.type))}：${escapeHtml(d.title)}"><div class="card-top"><button class="card-star ${d.favorite?'on':''}" data-star="${escapeHtml(d.id)}" title="收藏">${d.favorite?'★':'☆'}</button></div><h2>${highlightText(d.title)}</h2><p>${highlightText(summary(d))}</p><div class="card-tags">${(d.tags||[]).map(tag=>`<span class="tag">${highlightText(tag)}</span>`).join('')}</div><div class="card-bottom"><span class="category-chip"><i class="category-dot" style="background:${(categories.find(c=>c.name===d.category)||{}).color||'#aaa'}"></i>${highlightText(d.category||'未分类')}</span><span>${formatDate(d.updated)}</span></div></article>`).join('');if(more){more.hidden=visible.length>=results.length;more.textContent=`继续显示（剩余 ${Math.max(0,results.length-visible.length)} 份）`}document.querySelectorAll('.layout-option').forEach(button=>button.classList.toggle('active',button.dataset.layout===layoutMode));$('#emptyState').hidden=results.length>0;grid.hidden=results.length===0}
function setView(next){view=next;filter='all';activeDoc=null;visibleDocumentLimit=Number($('#pageSizeSelect')?.value||20);$('#readerView').hidden=true;$('#libraryView').hidden=false;document.querySelectorAll('.nav-item').forEach(e=>e.classList.toggle('active',(next==='library'&&e.dataset.view==='library')||(next==='latest'&&e.dataset.view==='latest')||(next==='favorites'&&e.dataset.view==='favorites')||(next==='recent'&&e.dataset.view==='recent')||(next==='trash'&&e.dataset.view==='trash')||(next===`category:${e.dataset.category}`)));document.querySelectorAll('.filter').forEach(e=>e.classList.toggle('active',e.dataset.filter==='all'));const data={library:['全部资料','沉淀每一个设计判断与技术细节。'],latest:['最新导入','按导入时间从新到旧排列，方便找到刚添加的资料。'],favorites:['我的收藏','只保留值得反复翻阅的资料。'],recent:['最近阅读','从上次停下的地方继续。'],trash:['回收站','已删除资料可在此恢复；附件会被保留。']};const [title,desc]=data[next]||[next.slice(9),`“${next.slice(9)}”分类下的全部资料。`];$('#viewTitle').textContent=title;$('#viewDescription').textContent=desc;renderDocs()}
async function openDoc(id,newTab=false){if(newTab){const doc=[...docs,...trash].find(item=>item.id===id);if(!doc)return;const url=new URL(window.location.href);url.searchParams.set('doc',id);const query=$('#searchInput').value.trim();if(query)url.searchParams.set('q',query);try{sessionStorage.setItem('motor-atlas-open-doc',JSON.stringify(doc))}catch(e){console.warn('无法传递阅读缓存',e)}const opened=window.open(url.href,'_blank');if(!opened)notify('浏览器阻止了新标签页，请允许此页面打开新标签页。','warn');return}activeDoc=[...docs,...trash].find(d=>d.id===id);if(!activeDoc){notify('未找到这份资料，可能已被删除。','warn');return}activeDoc.lastRead=Date.now();save();$('#readerView').className=`reader reader-${activeDoc.type}`;$('#libraryView').hidden=true;$('#readerView').hidden=false;$('#readerTitle').textContent=activeDoc.title;$('#readerMeta').textContent=`${typeLabel(activeDoc.type)} · ${activeDoc.category||'未分类'} · 更新于 ${formatDate(activeDoc.updated)}`;$('#readerTags').innerHTML=(activeDoc.tags||[]).map(x=>`<span class="tag">${escapeHtml(x)}</span>`).join('');$('#restoreButton').hidden=!trash.some(doc=>doc.id===activeDoc.id);if(isLanMode&&!activeDoc.contentLoaded){$('#articleContent').innerHTML='<p class="pdf-note">正在读取文档内容…</p>';try{const data=await remoteRequest(`/api/documents/${encodeURIComponent(id)}`);if(activeDoc?.id!==id)return;Object.assign(activeDoc,remoteDoc(data.document),{lastRead:activeDoc.lastRead})}catch(error){if(activeDoc?.id===id)$('#articleContent').innerHTML=`<p class="pdf-note">文档读取失败：${escapeHtml(error.message||'未知错误')}</p>`;return}}if(activeDoc.type==='pdf'&&activeDoc.pdfId){$('#articleContent').innerHTML='<p class="pdf-note">正在加载 PDF…</p>';renderStoredPdf(activeDoc).then(highlightArticle).catch(error=>{$('#articleContent').innerHTML=`<p class="pdf-note">PDF 加载失败：${escapeHtml(error.message||'未知错误')}</p>`})}else if(activeDoc.type==='presentation'&&activeDoc.presentationId){$('#articleContent').innerHTML='<p class="pdf-note">正在加载 PPTX…</p>';renderPresentation(activeDoc).then(highlightArticle).catch(error=>{$('#articleContent').innerHTML=`<p class="pdf-note">PPTX 加载失败：${escapeHtml(error.message||'未知错误')}</p>`})}else if(activeDoc.type==='sheet'){renderSheetContent(activeDoc.content)}else {$('#articleContent').innerHTML=sanitizeHtml(activeDoc.content);highlightArticle()}$('#favoriteButton').textContent=activeDoc.favorite?'★ 已收藏':'☆ 收藏';window.scrollTo({top:0,behavior:'smooth'})}
let commentLoadVersion=0,commentSubmitting=false,replyToComment=null;
function clearCommentReply(){replyToComment=null;$('#commentReplying').hidden=true;$('#commentReplyTarget').textContent='';$('#commentSubmit').textContent='发表评论';$('#commentInput').placeholder='写下你的问题、补充或经验…'}
function setCommentReply(comment){replyToComment={id:comment.id,username:comment.username||'该用户'};$('#commentReplyTarget').textContent=`回复 ${replyToComment.username}`;$('#commentReplying').hidden=false;$('#commentSubmit').textContent='发布回复';$('#commentInput').placeholder=`回复 ${replyToComment.username}…`;$('#commentInput').focus()}
function renderComments(comments=[]){const list=$('#commentList');list.replaceChildren();$('#commentCount').textContent=`${comments.length} 条`;if(!comments.length){const empty=document.createElement('p');empty.className='comment-empty';empty.textContent='暂无评论，欢迎留下你的问题或经验。';list.append(empty);return}const byId=new Map(comments.map(comment=>[Number(comment.id),comment])),children=new Map(),roots=[];comments.forEach(comment=>{const parent=Number(comment.parent_id);if(parent&&byId.has(parent)){const group=children.get(parent)||[];group.push(comment);children.set(parent,group)}else roots.push(comment)});const branch=(comment,depth=0)=>{const item=document.createElement('article');item.className='comment-item';const head=document.createElement('div');head.className='comment-item-head';const avatar=document.createElement('span');avatar.className='comment-avatar';avatar.textContent=(comment.username||'用').slice(0,1);const author=document.createElement('strong');author.className='comment-author';author.textContent=comment.username||'匿名用户';const time=document.createElement('time');time.className='comment-time';time.dateTime=comment.created_at;time.textContent=new Date(comment.created_at).toLocaleString('zh-CN');head.append(avatar,author,time);if(comment.can_reply){const reply=document.createElement('button');reply.type='button';reply.className='comment-reply';reply.dataset.replyComment=String(comment.id);reply.dataset.replyAuthor=comment.username||'';reply.textContent='回复';head.append(reply)}if(comment.can_delete){const remove=document.createElement('button');remove.type='button';remove.className='comment-delete';remove.dataset.deleteComment=String(comment.id);remove.textContent='删除';head.append(remove)}const content=document.createElement('p');content.className=`comment-content${comment.deleted_at?' comment-deleted':''}`;content.textContent=comment.deleted_at?'该评论已删除':comment.content;item.append(head,content);const replies=children.get(Number(comment.id))||[];if(replies.length){const replyList=document.createElement('div');replyList.className='comment-reply-list';replies.forEach(reply=>replyList.append(branch(reply,depth+1)));item.append(replyList)}return item};roots.forEach(comment=>list.append(branch(comment)))}
async function loadComments(docId){const version=++commentLoadVersion,section=$('#commentSection'),form=$('#commentForm'),list=$('#commentList'),submit=$('#commentSubmit');section.hidden=false;$('#commentInput').value='';clearCommentReply();if(!isLanMode){form.hidden=true;$('#commentCount').textContent='';list.innerHTML='<p class="comment-status">评论仅在局域网服务模式下可用。</p>';return}form.hidden=false;submit.disabled=true;$('#commentHint').textContent=`将以 ${currentUser.name||'当前账号'} 的身份发布`;$('#commentCount').textContent='加载中…';list.innerHTML='<p class="comment-status">正在加载评论…</p>';try{const data=await remoteRequest(`/api/documents/${encodeURIComponent(docId)}/comments`);if(version!==commentLoadVersion||activeDoc?.id!==docId)return;renderComments(data.comments||[])}catch(error){if(version!==commentLoadVersion)return;$('#commentCount').textContent='';list.innerHTML=`<p class="comment-status">评论加载失败：${escapeHtml(error.message||'未知错误')}</p>`}finally{if(version===commentLoadVersion&&activeDoc?.id===docId)submit.disabled=false}}
$('#cancelCommentReply').onclick=clearCommentReply;
$('#commentForm').addEventListener('submit',async event=>{event.preventDefault();if(!isLanMode||!activeDoc||commentSubmitting)return;const content=$('#commentInput').value.trim();if(!content)return;const isReply=!!replyToComment;commentSubmitting=true;const submit=$('#commentSubmit');submit.disabled=true;submit.textContent='正在发布…';try{await remoteRequest(`/api/documents/${encodeURIComponent(activeDoc.id)}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,parentId:replyToComment?.id??null})});$('#commentInput').value='';await loadComments(activeDoc.id);notify(isReply?'回复已发布':'评论已发布','success')}catch(error){notify(error.message||'评论发布失败','warn')}finally{commentSubmitting=false;if(activeDoc)submit.disabled=false;clearCommentReply()}});
$('#commentList').addEventListener('click',async event=>{const reply=event.target.closest('[data-reply-comment]');if(reply){setCommentReply({id:reply.dataset.replyComment,username:reply.dataset.replyAuthor});return}const button=event.target.closest('[data-delete-comment]');if(!button||!activeDoc||!isLanMode)return;const id=button.dataset.deleteComment;if(!confirm('删除这条评论？其下回复会继续保留。'))return;button.disabled=true;try{await remoteRequest(`/api/documents/${encodeURIComponent(activeDoc.id)}/comments/${encodeURIComponent(id)}`,{method:'DELETE'});await loadComments(activeDoc.id);notify('评论已删除','success')}catch(error){button.disabled=false;notify(error.message||'评论删除失败','warn')}});
const openDocumentWithHistory = openDoc;
openDoc = function(id,newTab=false){if(!newTab)disposeActivePdf();const result=openDocumentWithHistory(id,newTab);if(!newTab&&activeDoc){const history=getReadingHistory();history[activeDoc.id]=activeDoc.lastRead;saveReadingHistory(history);$('#readerMeta').textContent=`${typeLabel(activeDoc.type)} · ${activeDoc.category||'未分类'} · 上传者：${activeDoc.createdBy||(isLanMode?'系统迁移':currentUser.name)} · 更新于 ${formatDate(activeDoc.updated)}`;loadComments(activeDoc.id)}return result};
function closeReader(){disposeActivePdf();$('#readerView').hidden=true;$('#libraryView').hidden=false;activeDoc=null;renderDocs()}
async function remoteAttachmentBlob(doc,label){const response=await fetch(`/api/attachments/${encodeURIComponent(doc.attachmentId)}`,{credentials:'same-origin'});if(!response.ok)throw new Error(`${label} 原文件不存在`);return response.blob()}
function prepareImport(files){if(!requireEdit())return;pendingFiles=[...files];if(!pendingFiles.length)return;$('#importCategory').innerHTML=categories.map(c=>`<option value="${escapeHtml(c.name)}">${escapeHtml(c.name)}</option>`).join('');$('#importTags').value='';$('#importDialogTitle').textContent=pendingFiles.length>1?`批量导入 ${pendingFiles.length} 份资料`:'导入资料';$('#importFileSummary').textContent=`已选择 ${pendingFiles.length} 个文件：${pendingFiles.slice(0,3).map(f=>f.name).join('、')}${pendingFiles.length>3?' 等':''}`;$('#importDialog').showModal()}
async function importFiles(files,category,tags=[]){const list=[...files];if(!list.length||importingFiles)return;if(!requireEdit())return;let imported=0,failed=[];const importButton=$('#importButton'),emptyImport=$('#emptyImport'),originalButton=importButton.innerHTML;importingFiles=true;importButton.disabled=true;if(emptyImport)emptyImport.disabled=true;try{for(const [index,file] of list.entries()){importButton.textContent=`正在导入 ${index+1}/${list.length}`;notify(`正在处理 ${index+1}/${list.length}：${file.name}`,'info');try{const doc=await convertFile(file,category,tags);const attachment=doc.pdfBlob||doc.presentationBlob||doc.attachmentBlob;if(isLanMode)await createRemoteDoc(doc,attachment);if(doc.pdfBlob){if(!isLanMode)await savePdfBlob(doc.id,doc.pdfBlob);delete doc.pdfBlob}if(doc.presentationBlob){if(!isLanMode)await savePresentationBlob(doc.id,doc.presentationBlob);delete doc.presentationBlob}delete doc.attachmentBlob;docs.unshift(doc);imported++}catch(e){failed.push(`${file.name}：${e.message||'导入失败'}`)}}save();renderDocs();notify(failed.length?`已导入 ${imported} 份；${failed[0]}`:`已成功导入 ${imported} 份资料`,failed.length?'warn':'success')}finally{importingFiles=false;importButton.innerHTML=originalButton;importButton.disabled=!canEdit();if(emptyImport)emptyImport.disabled=!canEdit()}}
function needLibrary(name){if(!window[name])throw new Error('转换组件未从知识库服务器加载，请刷新页面或联系管理员');return window[name]}
async function convertFile(file,category,tags=[]){if(file.size>100*1024*1024)throw new Error('文件超过 100MB 上限');const name=file.name.replace(/\.[^.]+$/,'')||'未命名资料';const ext=(file.name.split('.').pop()||'').toLowerCase();let content='',type='document',pdfBlob=null,pdfPages=null,presentationBlob=null,attachmentBlob=null;if(['md','markdown'].includes(ext)){content=sanitizeHtml(needLibrary('marked').parse(await file.text()))}else if(['txt'].includes(ext)){content=`<pre>${escapeHtml(await file.text())}</pre>`}else if(['html','htm'].includes(ext)){content=sanitizeHtml(await file.text())}else if(ext==='docx'){content=sanitizeHtml(await needLibrary('mammoth').convertToHtml({arrayBuffer:await file.arrayBuffer()}).then(r=>r.value))}else if(['xlsx','xls'].includes(ext)){type='sheet';const wb=needLibrary('XLSX').read(await file.arrayBuffer(),{cellFormula:false,cellHTML:false});content=wb.SheetNames.map(n=>`<h2>${escapeHtml(n)}</h2>${sanitizeHtml(XLSX.utils.sheet_to_html(wb.Sheets[n]))}`).join('')}else if(ext==='pdf'){type='pdf';pdfPages=await inspectPdf(file);pdfBlob=file;content=`<p class="pdf-note">原始 PDF 已保存，将在打开时按需渲染（共 ${pdfPages} 页）。</p>`}else if(ext==='pptx'){type='presentation';presentationBlob=file;content='<p class="pdf-note">原始 PPTX 已保存，将在打开时转换为网页幻灯片。</p>'}else if(['png','jpg','jpeg','gif','webp'].includes(ext)){type='image';attachmentBlob=file;content=isLanMode?'<p class="pdf-note">原始图片已保存。</p>':`<img src="${await fileToDataURL(file)}" alt="${escapeHtml(name)}" loading="lazy" />`}else throw new Error('暂不支持旧版 .ppt，请另存为 .pptx 后导入');if(new Blob([content]).size>9_000_000)throw new Error('转换后的网页内容超过 9MB，请拆分文件后导入');const id=uuidv4();return {id,title:name,type,category:category||categories[0]?.name||'未分类',tags:[...new Set(tags)],updated:Date.now(),created:Date.now(),favorite:false,content,pdfId:pdfBlob?id:null,pdfPages,pdfBlob,presentationId:presentationBlob?id:null,presentationBlob,attachmentBlob}}
function fileToDataURL(f){return new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)})}
let pdfLibraryPromise=null,pdfRenderGeneration=0,activePdfCleanup=null;
async function getPdfLibrary(){if(!pdfLibraryPromise)pdfLibraryPromise=import('/vendor/pdf.mjs').then(pdfjs=>{pdfjs.GlobalWorkerOptions.workerSrc='/vendor/pdf.worker.mjs';return pdfjs});return pdfLibraryPromise}
function disposeActivePdf(){pdfRenderGeneration++;if(activePdfCleanup){activePdfCleanup();activePdfCleanup=null}}
async function inspectPdf(file){const pdfjs=await getPdfLibrary(),pdf=await pdfjs.getDocument({data:await file.arrayBuffer(),isEvalSupported:false}).promise;if(pdf.numPages>1000){await pdf.destroy();throw new Error('PDF 超过 1000 页，请拆分后再导入')}const pages=pdf.numPages;await pdf.destroy();return pages}
async function renderStoredPdf(doc){const generation=pdfRenderGeneration,blob=await getPdfBlob(doc.pdfId);if(!blob){$('#articleContent').innerHTML='<p class="pdf-note">未找到 PDF 原文件。若这是旧版资料，请重新导入该 PDF。</p>';return}const pdfjs=await getPdfLibrary(),pdf=await pdfjs.getDocument({data:await blob.arrayBuffer(),isEvalSupported:false}).promise;if(generation!==pdfRenderGeneration){await pdf.destroy();return}$('#articleContent').innerHTML=`<div class="pdf-toolbar"><span id="pdfPageInfo">正在准备 ${pdf.numPages} 页…</span></div><div id="pdfPages"></div>`;const info=$('#pdfPageInfo'),pages=$('#pdfPages'),rendered=new Set(),rendering=new Set();let observer=null,destroyed=false;const cleanup=()=>{if(destroyed)return;destroyed=true;observer?.disconnect();pdf.destroy().catch(()=>{})};activePdfCleanup=cleanup;const renderPage=async shell=>{const pageNumber=Number(shell.dataset.page);if(destroyed||rendered.has(pageNumber)||rendering.has(pageNumber))return;rendering.add(pageNumber);try{const page=await pdf.getPage(pageNumber);if(destroyed)return;const base=page.getViewport({scale:1}),available=Math.max(320,pages.clientWidth||900),cssScale=Math.min(3,available/base.width),viewport=page.getViewport({scale:cssScale}),outputScale=Math.min(window.devicePixelRatio||1,3),canvas=document.createElement('canvas');canvas.className='pdf-page';canvas.width=Math.floor(viewport.width*outputScale);canvas.height=Math.floor(viewport.height*outputScale);canvas.style.width=`${Math.floor(viewport.width)}px`;canvas.style.height=`${Math.floor(viewport.height)}px`;canvas.setAttribute('aria-label',`PDF 第 ${pageNumber} 页`);shell.replaceChildren(canvas);shell.classList.add('rendered');await page.render({canvasContext:canvas.getContext('2d'),viewport,transform:outputScale===1?null:[outputScale,0,0,outputScale,0,0]}).promise;rendered.add(pageNumber);info.textContent=`已加载 ${rendered.size} / ${pdf.numPages} 页`;if(rendered.size===pdf.numPages){info.textContent=`PDF 共 ${pdf.numPages} 页，已全部渲染`;cleanup();activePdfCleanup=null}}finally{rendering.delete(pageNumber)}};for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){const shell=document.createElement('section');shell.className='pdf-page-shell';shell.dataset.page=String(pageNumber);shell.innerHTML=`<span>第 ${pageNumber} 页</span>`;pages.append(shell)}if('IntersectionObserver'in window){observer=new IntersectionObserver(entries=>entries.filter(entry=>entry.isIntersecting).forEach(entry=>{observer.unobserve(entry.target);renderPage(entry.target)}),{rootMargin:'1200px 0px'});pages.querySelectorAll('.pdf-page-shell').forEach(shell=>observer.observe(shell))}else{for(const shell of pages.querySelectorAll('.pdf-page-shell'))await renderPage(shell)}}
async function renderPresentation(doc){if(!window.jQuery||!jQuery.fn.pptxToHtml)throw new Error('PPTX 渲染组件未加载，请刷新页面');let url='',revoke=false;if(isLanMode){url=`/api/attachments/${encodeURIComponent(doc.presentationId)}`}else{const blob=await getPresentationBlob(doc.presentationId);if(!blob)throw new Error('未找到 PPTX 原文件，请重新导入');url=URL.createObjectURL(blob);revoke=true}$('#articleContent').innerHTML='<div id="pptxViewer" class="pptx-viewer"></div>';try{jQuery('#pptxViewer').pptxToHtml({pptxFileUrl:url,slidesScale:'100%',slideMode:false,keyBoardShortCut:false,mediaProcess:true});if(revoke)setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(error){if(revoke)URL.revokeObjectURL(url);throw error}}

function renderSheetContent(html){const parser=new DOMParser();const dom=parser.parseFromString(html,'text/html');const h2s=[...dom.querySelectorAll('h2')];const tables=[...dom.querySelectorAll('table')];const sheets=h2s.map((h,i)=>({name:h.textContent.trim(),html:tables[i]?tables[i].outerHTML:''}));if(!sheets.length){$('#articleContent').innerHTML=sanitizeHtml(html);highlightArticle();return}let result='<div class="sheet-viewer"><div class="sheet-toolbar"><div class="sheet-tabs">';sheets.forEach((s,i)=>{result+='<button class="sheet-tab'+(i===0?' active':'')+'" data-sheet="'+i+'">'+escapeHtml(s.name)+'</button>'});result+='</div><div class="sheet-zoom"><button class="zoom-btn" data-zoom="out">−</button><span class="zoom-label">100%</span><button class="zoom-btn" data-zoom="in">＋</button><button class="zoom-btn zoom-fit" data-zoom="fit">适配</button></div></div><div class="sheet-panels">';sheets.forEach((s,i)=>{result+='<div class="sheet-panel'+(i===0?' active':'')+'" data-panel="'+i+'"><div class="sheet-scroll"><div class="sheet-table-wrap">'+s.html+'</div></div></div>'});result+='</div></div>';const el=document.createElement('div');el.innerHTML=result;const viewer=el.firstElementChild;viewer.querySelector('.sheet-tabs').addEventListener('click',e=>{const btn=e.target.closest('.sheet-tab');if(!btn)return;const idx=btn.dataset.sheet;viewer.querySelectorAll('.sheet-tab').forEach(t=>t.classList.remove('active'));viewer.querySelectorAll('.sheet-panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');const panel=viewer.querySelector('[data-panel="'+idx+'"]');if(panel)panel.classList.add('active')});const zoomLabel=viewer.querySelector('.zoom-label');viewer.querySelector('.sheet-zoom').addEventListener('click',e=>{const btn=e.target.closest('.zoom-btn');if(!btn)return;const activePanel=viewer.querySelector('.sheet-panel.active');if(!activePanel)return;const wrap=activePanel.querySelector('.sheet-table-wrap');const cur=parseFloat(wrap.dataset.zoom||'1');let next=cur;if(btn.dataset.zoom==='in')next=Math.min(2,cur+0.15);else if(btn.dataset.zoom==='out')next=Math.max(0.3,cur-0.15);else if(btn.dataset.zoom==='fit'){const scroll=activePanel.querySelector('.sheet-scroll');const table=wrap.querySelector('table');if(table&&scroll){next=Math.min(1,Math.max(0.3,(scroll.clientWidth-2)/table.offsetWidth));next=Math.round(next*100)/100}}wrap.style.transform='scale('+next+')';wrap.style.transformOrigin='top left';wrap.dataset.zoom=next;zoomLabel.textContent=Math.round(next*100)+'%'});$('#articleContent').innerHTML='';$('#articleContent').appendChild(viewer);highlightArticle()}
function newNote(){const dialog=$('#noteDialog');$('#noteForm').reset();renderCategories();$('#noteTitle').value='';$('#noteTags').value='';$('#noteContent').value='';dialog.showModal();setTimeout(()=>$('#noteTitle').focus(),0)}
$('#importButton').onclick=()=>$('#fileInput').click();$('#emptyImport').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{prepareImport(e.target.files);e.target.value=''};$('#importForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel'){pendingFiles=[];return}e.preventDefault();const files=pendingFiles,tags=parseTags($('#importTags').value);pendingFiles=[];$('#importDialog').close();importFiles(files,$('#importCategory').value,tags)});$('#newNote').onclick=newNote;$('#closeNote').onclick=()=>$('#noteDialog').close();$('#cancelNote').onclick=()=>$('#noteDialog').close();$('#noteForm').addEventListener('submit',async e=>{e.preventDefault();if(noteSaving)return;const title=$('#noteTitle').value.trim().replace(/\s+/g,' '),source=$('#noteContent').value.trim(),category=$('#noteCategory').value,tags=parseTags($('#noteTags').value);if(!title||!source){notify('请填写笔记标题和内容','warn');return}noteSaving=true;const saveButton=$('#saveNote');saveButton.disabled=true;saveButton.textContent='正在保存…';try{const doc={id:uuidv4(),title,type:'document',category,tags:[...new Set(['笔记',...tags])],updated:Date.now(),created:Date.now(),favorite:false,content:sanitizeHtml(needLibrary('marked').parse(source))};if(isLanMode)await createRemoteDoc(doc);docs.unshift(doc);if(!save()){docs.shift();return}$('#noteDialog').close();renderDocs();notify('笔记已保存','success')}catch(err){notify(err.message||'笔记保存失败','warn')}finally{noteSaving=false;saveButton.disabled=false;saveButton.textContent='保存笔记'}});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#categoryList').onclick=e=>{const b=e.target.closest('[data-category]');if(b)setView(`category:${b.dataset.category}`)};$('#addCategory').onclick=()=>{const name=prompt('分类名称');if(name&& !categories.some(c=>c.name===name)){categories.push({name,color:'#8c9d7e'});save();renderCategories();renderDocs()}};$('#documentGrid').onclick=async e=>{const star=e.target.closest('[data-star]');if(star){const d=docs.find(x=>x.id===star.dataset.star);if(!d)return;const previous=d.favorite;d.favorite=!previous;try{await updateRemoteFavorite(d);save();renderDocs()}catch(error){d.favorite=previous;notify(error.message||'收藏同步失败','warn')}return}const card=e.target.closest('.doc-card');if(card)openDoc(card.dataset.id,true)};let searchTimer=null;$('#searchInput').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(refreshRemoteSearch,220)};$('#sortSelect').onchange=()=>{visibleDocumentLimit=Number($('#pageSizeSelect')?.value||20);renderDocs()};$('#pageSizeSelect').onchange=()=>{visibleDocumentLimit=Number($('#pageSizeSelect').value);renderDocs()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;visibleDocumentLimit=Number($('#pageSizeSelect')?.value||20);document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderDocs()});document.querySelectorAll('.layout-option').forEach(button=>button.onclick=()=>{layoutMode=button.dataset.layout;renderDocs()});$('#loadMoreDocs').onclick=()=>{visibleDocumentLimit+=Number($('#pageSizeSelect')?.value||20);renderDocs()};$('#themeToggle').onclick=()=>document.body.classList.toggle('dark');$('#backToLibrary').onclick=closeReader;$('#favoriteButton').onclick=()=>{activeDoc.favorite=!activeDoc.favorite;save();$('#favoriteButton').textContent=activeDoc.favorite?'★ 已收藏':'☆ 收藏';renderDocs()};$('#deleteButton').onclick=()=>{if(confirm(`删除“${activeDoc.title}”？`)){const pdfId=activeDoc.pdfId,presentationId=activeDoc.presentationId;docs=docs.filter(d=>d.id!==activeDoc.id);save();if(pdfId)deletePdfBlob(pdfId);if(presentationId)deletePresentationBlob(presentationId);closeReader()}};$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');
let dragDepth=0;const isFileDrag=e=>[...(e.dataTransfer?.types||[])].includes('Files');window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}if(e.key==='Escape')$('#sidebar').classList.remove('open')});window.addEventListener('dragenter',e=>{if(!isFileDrag(e))return;e.preventDefault();dragDepth++;$('#dropOverlay').classList.add('show')});window.addEventListener('dragover',e=>{if(isFileDrag(e))e.preventDefault()});window.addEventListener('dragleave',e=>{if(!isFileDrag(e))return;e.preventDefault();dragDepth--;if(dragDepth<=0){dragDepth=0;$('#dropOverlay').classList.remove('show')}});window.addEventListener('drop',e=>{if(!isFileDrag(e))return;e.preventDefault();dragDepth=0;$('#dropOverlay').classList.remove('show');prepareImport(e.dataTransfer.files)});
const pptFilter=document.createElement('button');pptFilter.className='filter';pptFilter.dataset.filter='presentation';pptFilter.textContent='PPT';pptFilter.onclick=()=>{filter='presentation';document.querySelectorAll('.filter').forEach(item=>item.classList.toggle('active',item===pptFilter));renderDocs()};document.querySelector('[data-filter="pdf"]')?.after(pptFilter);renderCategories();renderDocs();const requestedDoc=new URLSearchParams(window.location.search).get('doc');let transferredDoc=null;try{transferredDoc=JSON.parse(sessionStorage.getItem('motor-atlas-open-doc')||'null');sessionStorage.removeItem('motor-atlas-open-doc')}catch(e){console.warn('阅读缓存不可用',e)}if(requestedDoc&&transferredDoc&&transferredDoc.id===requestedDoc&&!docs.some(doc=>doc.id===requestedDoc)){docs.unshift(transferredDoc);save()}if(requestedDoc)openDoc(requestedDoc);if(!isLanMode)loadFromDatabase().then(saved=>{if(!saved)return saveToDatabase();if(Array.isArray(saved.docs)&&saved.docs.length){docs=saved.docs;categories=Array.isArray(saved.categories)&&saved.categories.length?saved.categories:categories;renderDocs();if(requestedDoc)openDoc(requestedDoc)}});
